In [1]:
import numpy as np

### **`Vectors`**

In [2]:
# Scalar Operations
# -----------------
x = np.array([10, 20, 30])
scalar = 3
print(x + scalar)

[13 23 33]


In [3]:
# Element-Wise Operations
# -----------------------
x = np.array([100,200,300])
y = np.array([10, 20, 30])

print(f"x + y = {x+y}")
print(f"x - y = {x+y}")
print(f"x / y = {x/y}")

print(f"x * y = {x*y}") # This is also called the Hadamard Product


x + y = [110 220 330]
x - y = [110 220 330]
x / y = [10. 10. 10.]
x * y = [1000 4000 9000]


In [4]:
# Dot Product
# -----------
x = np.array([100,200,300])
y = np.array([10, 20, 30])
print(f"The dot-product is: {np.dot(x,y)}")

The dot-product is: 14000


In [5]:
# Hadamard Product
# ----------------
x = np.array([2,4,6])
y = np.array([3,5,7])
print(f"The hadamard-product is: {x*y}")

The hadamard-product is: [ 6 20 42]


### **`Matrices`**

In [6]:
matrix = np.array([
    [1, 2, 3], 
    [5, 6, 7]
])

print("The Matrix is: \n", matrix)
print("Shape of the matrix: ", matrix.shape)
print("Number of Rows:      ", matrix.shape[0])
print("Number of Columns:   ", matrix.shape[1])

The Matrix is: 
 [[1 2 3]
 [5 6 7]]
Shape of the matrix:  (2, 3)
Number of Rows:       2
Number of Columns:    3


In [7]:
# Scalar Operations on Matrices
# -----------------------------
matrix = np.array([
    [1, 2, 3], 
    [5, 6, 7]
])

print(matrix+10)

[[11 12 13]
 [15 16 17]]


In [8]:
# Element Wise operations
# -----------------------
mat1 = np.array([[1,2,3], [5,6,7]])
mat2 = np.array([[4,2,1], [9,5,7]])

print(f"matrix 1 + matrix 2: \n {mat1+mat2}")
print(f"matrix 1 - matrix 2: \n {mat1-mat2}")

matrix 1 + matrix 2: 
 [[ 5  4  4]
 [14 11 14]]
matrix 1 - matrix 2: 
 [[-3  0  2]
 [-4  1  0]]


In [9]:
# Hadamard Product
# ----------------
mat1 = np.array([[1,2,3], [5,6,7]])
mat2 = np.array([[4,2,1], [9,5,7]])
print("Hadamard Product: \n", mat1*mat2)

Hadamard Product: 
 [[ 4  4  3]
 [45 30 49]]


In [10]:
# Transpose of a Matrix
# ---------------------
matrix = np.array([
    [1, 2, 3], 
    [5, 6, 7]
])

print("Original Matrix is :")
print(matrix)
print("Transposed Matrix is :")
print(matrix.T)

Original Matrix is :
[[1 2 3]
 [5 6 7]]
Transposed Matrix is :
[[1 5]
 [2 6]
 [3 7]]


### **`Matrix Multiplication`**


In [18]:
def matrix_multiplication(mat1, mat2):
    r1 = mat1.shape[0]
    r2 = mat2.shape[0]
    c1 = mat1.shape[1]
    c2 = mat2.shape[1]
    
    if c1 != r2: # Matrix is Valid
        raise ValueError("Matrices cannot be multiplied. Incompatible dimensions.")
    
    # Create an empty result matrix
    res_mat = np.zeros((r1, c2))
    
    # Perform matrix multiplication
    for i in range(r1):
        for j in range(c2):
            for k in range(r2):
                res_mat[i][j] += mat1[i][k] * mat2[k][j]   

    return res_mat

if __name__ == "__main__":
    print("Matrix Multiplication!!")
    mat1 = np.array([[2,5,12], 
                     [4,8,9]])
    mat2 = np.array([[1,3,5], 
                     [8,5,6],
                     [4,3,1]])
    res_matrix = matrix_multiplication(mat1=mat1, mat2=mat2)
    print(res_matrix)


Matrix Multiplication!!
[[ 90.  67.  52.]
 [104.  79.  77.]]


----------------------------------------------