In [1]:
import numpy as np

### **`Vectors`**

In [5]:
# Scalar Operations
# -----------------
x = np.array([10, 20, 30])
scalar = 3
print(x + scalar)

[13 23 33]


In [4]:
# Element-Wise Operations
# -----------------------
x = np.array([100,200,300])
y = np.array([10, 20, 30])

print(f"x + y = {x+y}")
print(f"x - y = {x+y}")
print(f"x / y = {x/y}")

print(f"x * y = {x*y}") # This is also called the Hadamard Product


x + y = [110 220 330]
x - y = [110 220 330]
x / y = [10. 10. 10.]
x * y = [1000 4000 9000]


In [6]:
# Dot Product
# -----------
x = np.array([100,200,300])
y = np.array([10, 20, 30])
print(f"The dot-product is: {np.dot(x,y)}")

The dot-product is: 14000


In [7]:
# Hadamard Product
# ----------------
x = np.array([2,4,6])
y = np.array([3,5,7])
print(f"The hadamard-product is: {x*y}")

The hadamard-product is: [ 6 20 42]


### **`Matrices`**

In [10]:
matrix = np.array([
    [1, 2, 3], 
    [5, 6, 7]
])

print("The Matrix is: \n", matrix)
print("Shape of the matrix: ", matrix.shape)
print("Number of Rows:      ", matrix.shape[0])
print("Number of Columns:   ", matrix.shape[1])

The Matrix is: 
 [[1 2 3]
 [5 6 7]]
Shape of the matrix:  (2, 3)
Number of Rows:       2
Number of Columns:    3


In [11]:
# Scalar Operations on Matrices
# -----------------------------
matrix = np.array([
    [1, 2, 3], 
    [5, 6, 7]
])

print(matrix+10)

[[11 12 13]
 [15 16 17]]


In [16]:
# Element Wise operations
# -----------------------
mat1 = np.array([[1,2,3], [5,6,7]])
mat2 = np.array([[4,2,1], [9,5,7]])

print(f"matrix 1 + matrix 2: \n {mat1+mat2}")
print(f"matrix 1 - matrix 2: \n {mat1-mat2}")

matrix 1 + matrix 2: 
 [[ 5  4  4]
 [14 11 14]]
matrix 1 - matrix 2: 
 [[-3  0  2]
 [-4  1  0]]


In [17]:
# Hadamard Product
# ----------------
mat1 = np.array([[1,2,3], [5,6,7]])
mat2 = np.array([[4,2,1], [9,5,7]])
print("Hadamard Product: \n", mat1*mat2)

Hadamard Product: 
 [[ 4  4  3]
 [45 30 49]]


In [18]:
# Transpose of a Matrix
# ---------------------
matrix = np.array([
    [1, 2, 3], 
    [5, 6, 7]
])

print("Original Matrix is :")
print(matrix)
print("Transposed Matrix is :")
print(matrix.T)

Original Matrix is :
[[1 2 3]
 [5 6 7]]
Transposed Matrix is :
[[1 5]
 [2 6]
 [3 7]]
